# =============================================================================
# Forgejo Actions: Build and Push Modular Container Images
# =============================================================================
# Builds base image, flavor images, and addon images
# Uses plain shell commands - no Node.js required
# =============================================================================

name: Build Container Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.forgejo/workflows/build-containers.yml'
    tags:
      - 'v*'
  
  workflow_dispatch:
    inputs:
      build_type:
        description: 'What to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - base
          - flavors
          - addons
      flavor:
        description: 'Specific flavor (if build_type=flavors)'
        required: false
        type: choice
        options:
          - all
          - js
          - python
          - go
          - rust
          - fullstack
          - polyglot
      addon:
        description: 'Specific addon (if build_type=addons)'
        required: false
        type: choice
        options:
          - all
          - gui
          - code-server
          - databases
          - cloud
          - gpu

env:
  REGISTRY: forgejo.superchotu.com
  OWNER: rakeshgangwar

jobs:
  # =============================================================================
  # Build Base Image
  # =============================================================================
  build-base:
    name: Build Base Image
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'base' || github.event.inputs.build_type == '' }}
    outputs:
      version: ${{ steps.version.outputs.VERSION }}
    steps:
      - name: Checkout repository
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://forgejo.superchotu.com/${{ github.repository }}.git .

      - name: Read version
        id: version
        run: |
          VERSION=$(cat docker/VERSION 2>/dev/null | tr -d '\n' || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Base image
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER }}/codeopen-base"
          
          echo "Building $IMAGE_NAME:$VERSION"
          
          docker build \
            --build-arg CONTAINER_VERSION=$VERSION \
            -t "$IMAGE_NAME:$VERSION" \
            -t "$IMAGE_NAME:latest" \
            -f ./docker/base/Dockerfile \
            ./docker/base
          
          echo "Pushing $IMAGE_NAME:$VERSION"
          docker push "$IMAGE_NAME:$VERSION"
          
          echo "Pushing $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest" || echo "Warning: Failed to push latest tag"
          
          echo "Base image pushed successfully"

  # =============================================================================
  # Build Flavor Images (depend on base)
  # =============================================================================
  build-flavors:
    name: Build Flavor Images
    runs-on: ubuntu-latest
    needs: build-base
    if: ${{ always() && (github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'flavors' || github.event.inputs.build_type == '') }}
    strategy:
      fail-fast: false
      matrix:
        flavor: [js, python, go, rust, fullstack, polyglot]
    steps:
      - name: Check if should build this flavor
        id: should-build
        run: |
          SELECTED_FLAVOR="${{ github.event.inputs.flavor }}"
          CURRENT_FLAVOR="${{ matrix.flavor }}"
          if [ "$SELECTED_FLAVOR" == "" ] || [ "$SELECTED_FLAVOR" == "all" ] || [ "$SELECTED_FLAVOR" == "$CURRENT_FLAVOR" ]; then
            echo "BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "BUILD=false" >> $GITHUB_OUTPUT
            echo "Skipping $CURRENT_FLAVOR (not selected)"
          fi

      - name: Checkout repository
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://forgejo.superchotu.com/${{ github.repository }}.git .

      - name: Read version
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          VERSION=$(cat docker/VERSION 2>/dev/null | tr -d '\n' || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Forgejo Registry
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push ${{ matrix.flavor }} flavor
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          FLAVOR="${{ matrix.flavor }}"
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER }}/codeopen-${FLAVOR}"
          BASE_IMAGE="${{ env.REGISTRY }}/${{ env.OWNER }}/codeopen-base:$VERSION"
          
          echo "Building $IMAGE_NAME:$VERSION (from $BASE_IMAGE)"
          
          docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            --build-arg CONTAINER_VERSION=$VERSION \
            -t "$IMAGE_NAME:$VERSION" \
            -t "$IMAGE_NAME:latest" \
            -f "./docker/flavors/${FLAVOR}/Dockerfile" \
            "./docker/flavors/${FLAVOR}"
          
          echo "Pushing $IMAGE_NAME:$VERSION"
          docker push "$IMAGE_NAME:$VERSION"
          
          echo "Pushing $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest" || echo "Warning: Failed to push latest tag"
          
          echo "$FLAVOR flavor image pushed successfully"

  # =============================================================================
  # Build Addon Images (depend on base)
  # =============================================================================
  build-addons:
    name: Build Addon Images
    runs-on: ubuntu-latest
    needs: build-base
    if: ${{ always() && (github.event.inputs.build_type == 'all' || github.event.inputs.build_type == 'addons' || github.event.inputs.build_type == '') }}
    strategy:
      fail-fast: false
      matrix:
        addon: [gui, code-server, databases, cloud, gpu]
    steps:
      - name: Check if should build this addon
        id: should-build
        run: |
          SELECTED_ADDON="${{ github.event.inputs.addon }}"
          CURRENT_ADDON="${{ matrix.addon }}"
          if [ "$SELECTED_ADDON" == "" ] || [ "$SELECTED_ADDON" == "all" ] || [ "$SELECTED_ADDON" == "$CURRENT_ADDON" ]; then
            echo "BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "BUILD=false" >> $GITHUB_OUTPUT
            echo "Skipping $CURRENT_ADDON (not selected)"
          fi

      - name: Checkout repository
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://forgejo.superchotu.com/${{ github.repository }}.git .

      - name: Read version
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          VERSION=$(cat docker/VERSION 2>/dev/null | tr -d '\n' || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Login to Forgejo Registry
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push ${{ matrix.addon }} addon
        if: steps.should-build.outputs.BUILD == 'true'
        run: |
          ADDON="${{ matrix.addon }}"
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER }}/codeopen-addon-${ADDON}"
          BASE_IMAGE="${{ env.REGISTRY }}/${{ env.OWNER }}/codeopen-base:$VERSION"
          
          echo "Building $IMAGE_NAME:$VERSION (from $BASE_IMAGE)"
          
          docker build \
            --build-arg BASE_IMAGE=$BASE_IMAGE \
            --build-arg CONTAINER_VERSION=$VERSION \
            -t "$IMAGE_NAME:$VERSION" \
            -t "$IMAGE_NAME:latest" \
            -f "./docker/addons/${ADDON}/Dockerfile" \
            "./docker/addons/${ADDON}"
          
          echo "Pushing $IMAGE_NAME:$VERSION"
          docker push "$IMAGE_NAME:$VERSION"
          
          echo "Pushing $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest" || echo "Warning: Failed to push latest tag"
          
          echo "$ADDON addon image pushed successfully"

  # =============================================================================
  # Build Summary
  # =============================================================================
  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-base, build-flavors, build-addons]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Build Summary"
          echo ""
          echo "### Results"
          echo "- Base: ${{ needs.build-base.result }}"
          echo "- Flavors: ${{ needs.build-flavors.result }}"
          echo "- Addons: ${{ needs.build-addons.result }}"
          echo ""
          echo "### Images Built"
          echo "- codeopen-base"
          echo "- codeopen-js, codeopen-python, codeopen-go, codeopen-rust, codeopen-fullstack, codeopen-polyglot"
          echo "- codeopen-addon-gui, codeopen-addon-code-server, codeopen-addon-databases, codeopen-addon-cloud, codeopen-addon-gpu"
