# =============================================================================
# Forgejo Actions: Build and Push OpenCode Container Images
# =============================================================================
# Uses plain shell commands - no Node.js required
# =============================================================================

name: Build Container Images

on:
  push:
    branches:
      - main
    paths:
      - 'docker/**'
      - '.forgejo/workflows/build-containers.yml'
    tags:
      - 'v*'
  
  workflow_dispatch:
    inputs:
      image_type:
        description: 'Image to build'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - cli
          - desktop

env:
  REGISTRY: forgejo.superchotu.com
  OWNER: rakeshgangwar

jobs:
  build-cli:
    name: Build CLI Image
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.image_type == 'all' || github.event.inputs.image_type == 'cli' || github.event.inputs.image_type == '' }}
    steps:
      - name: Checkout repository
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://forgejo.superchotu.com/${{ github.repository }}.git .

      - name: Read version
        id: version
        run: |
          VERSION=$(cat docker/VERSION 2>/dev/null | tr -d '\n' || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push CLI image
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER }}/opencode-cli"
          
          echo "Building $IMAGE_NAME:$VERSION"
          
          docker build \
            --build-arg CONTAINER_VERSION=$VERSION \
            -t "$IMAGE_NAME:$VERSION" \
            -t "$IMAGE_NAME:latest" \
            -f ./docker/opencode-cli/Dockerfile \
            ./docker/opencode-cli
          
          echo "Pushing $IMAGE_NAME:$VERSION"
          docker push "$IMAGE_NAME:$VERSION"
          
          echo "Pushing $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest" || echo "Warning: Failed to push latest tag"
          
          echo "CLI image pushed successfully"

  build-desktop:
    name: Build Desktop Image
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.image_type == 'all' || github.event.inputs.image_type == 'desktop' || github.event.inputs.image_type == '' }}
    steps:
      - name: Checkout repository
        run: |
          git clone --depth 1 --branch ${{ github.ref_name }} https://forgejo.superchotu.com/${{ github.repository }}.git .

      - name: Read version
        id: version
        run: |
          VERSION=$(cat docker/VERSION 2>/dev/null | tr -d '\n' || echo "0.0.1")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Login to Forgejo Registry
        run: |
          echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ${{ env.REGISTRY }} -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Build and push Desktop image
        run: |
          IMAGE_NAME="${{ env.REGISTRY }}/${{ env.OWNER }}/opencode-desktop"
          
          echo "Building $IMAGE_NAME:$VERSION"
          
          docker build \
            --build-arg CONTAINER_VERSION=$VERSION \
            -t "$IMAGE_NAME:$VERSION" \
            -t "$IMAGE_NAME:latest" \
            -f ./docker/opencode-desktop/Dockerfile \
            ./docker/opencode-desktop
          
          echo "Pushing $IMAGE_NAME:$VERSION"
          docker push "$IMAGE_NAME:$VERSION"
          
          echo "Pushing $IMAGE_NAME:latest"
          docker push "$IMAGE_NAME:latest" || echo "Warning: Failed to push latest tag"
          
          echo "Desktop image pushed successfully"

  summary:
    name: Build Summary
    runs-on: ubuntu-latest
    needs: [build-cli, build-desktop]
    if: always()
    steps:
      - name: Summary
        run: |
          echo "## Build Summary"
          echo "CLI: ${{ needs.build-cli.result }}"
          echo "Desktop: ${{ needs.build-desktop.result }}"
