#!/usr/bin/env bun
/**
 * OpenCode Agent Generator
 * 
 * Generates TypeScript module with agent definitions for database seeding.
 * 
 * Usage: pnpm run generate:opencode-agents
 * Output: packages/agents/src/generated/opencode-agents.ts
 */

import { writeFile, mkdir } from "node:fs/promises"
import { join, dirname } from "node:path"
import { fileURLToPath } from "node:url"
import { ALL_AGENTS } from "../src/library"
import type { AgentConfig, ToolRestrictions } from "../src/core/types"

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const OUTPUT_DIR = join(__dirname, "../src/generated")
const OUTPUT_FILE = join(OUTPUT_DIR, "opencode-agents.ts")

const SQUAD_COLORS: Record<string, string> = {
  orchestration: "#00D9FF",
  development: "#00FF9F",
  product: "#FF00FF",
  operations: "#FFB800",
  security: "#FF0054",
  data: "#00BFFF",
}

function generateFrontmatter(agent: AgentConfig): string {
  const lines: string[] = ["---"]
  
  const shortDesc = agent.delegationTriggers?.[0] 
    ? `${agent.role} - ${capitalizeFirst(agent.delegationTriggers[0])}`
    : agent.role
  lines.push(`description: "${shortDesc}"`)
  
  lines.push("mode: primary")
  lines.push(`model: ${agent.model}`)
  lines.push(`temperature: ${agent.temperature}`)
  
  const color = SQUAD_COLORS[agent.squad] || "#00D9FF"
  lines.push(`color: "${color}"`)
  
  lines.push("tools:")
  lines.push(`  write: ${agent.tools?.write ?? true}`)
  lines.push(`  edit: ${agent.tools?.edit ?? true}`)
  lines.push(`  bash: ${agent.tools?.execute ?? true}`)
  lines.push(`  webfetch: ${agent.tools?.network ?? true}`)
  lines.push(`  read: true`)
  lines.push(`  glob: true`)
  lines.push(`  grep: true`)
  
  const deniedTools = getDeniedTools(agent.tools)
  if (deniedTools.length > 0) {
    lines.push("permission:")
    for (const tool of deniedTools) {
      lines.push(`  ${tool}: deny`)
    }
  }
  
  lines.push("---")
  return lines.join("\n")
}

function getDeniedTools(tools?: ToolRestrictions): string[] {
  if (!tools) return []
  
  const denied: string[] = []
  if (tools.write === false) denied.push("write")
  if (tools.edit === false) denied.push("edit")
  if (tools.execute === false) denied.push("bash")
  if (tools.network === false) denied.push("webfetch")
  if (tools.delete === false) denied.push("delete")
  
  return denied
}

function capitalizeFirst(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1)
}

function generateAgentMarkdown(agent: AgentConfig): string {
  const frontmatter = generateFrontmatter(agent)
  
  const header = `
# ${agent.emoji || "🤖"} ${agent.name} - ${agent.role}

> **Squad**: ${capitalizeFirst(agent.squad)} | **Tier**: ${capitalizeFirst(agent.tier)} | **Intelligence**: Level ${agent.intelligenceLevel}/5

`
  
  return frontmatter + "\n" + header + agent.systemPrompt
}

interface OpenCodeAgentDefinition {
  name: string
  role: string
  emoji: string
  squad: string
  content: string
}

function generateTypeScriptModule(agents: OpenCodeAgentDefinition[]): string {
  const agentEntries = agents.map(agent => {
    const escapedContent = agent.content
      .replace(/\\/g, '\\\\')
      .replace(/`/g, '\\`')
      .replace(/\$\{/g, '\\${')
    
    return `  {
    name: "${agent.name.toLowerCase()}",
    role: "${agent.role}",
    emoji: "${agent.emoji}",
    squad: "${agent.squad}",
    content: \`${escapedContent}\`,
  }`
  }).join(',\n')

  return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by: pnpm run generate:opencode-agents
 * 
 * Contains OpenCode-format agent definitions for database seeding.
 */

export interface OpenCodeAgentDefinition {
  name: string
  role: string
  emoji: string
  squad: string
  content: string
}

export const OPENCODE_AGENTS: OpenCodeAgentDefinition[] = [
${agentEntries}
]

export const AGENT_NAMES = [${agents.map(a => `"${a.name.toLowerCase()}"`).join(', ')}] as const
export type AgentName = typeof AGENT_NAMES[number]
`
}

async function main() {
  console.log("🤖 OpenCode Agent Generator")
  console.log("=" .repeat(50))
  console.log()
  
  await mkdir(OUTPUT_DIR, { recursive: true })
  
  console.log("📝 Converting agents to OpenCode format:")
  console.log()
  
  const agentDefinitions: OpenCodeAgentDefinition[] = []
  
  for (const agent of ALL_AGENTS) {
    const content = generateAgentMarkdown(agent)
    
    agentDefinitions.push({
      name: agent.name,
      role: agent.role,
      emoji: agent.emoji || "🤖",
      squad: agent.squad,
      content,
    })
    
    const lines = content.split("\n").length
    const tools = agent.tools
    const perms = [
      tools?.write !== false ? "W" : "-",
      tools?.edit !== false ? "E" : "-",
      tools?.execute !== false ? "X" : "-",
      tools?.network !== false ? "N" : "-",
    ].join("")
    
    console.log(`   ${agent.emoji || "🤖"} ${agent.name.padEnd(10)} ${agent.role.padEnd(25)} [${perms}] (${lines} lines)`)
  }
  
  const moduleContent = generateTypeScriptModule(agentDefinitions)
  await writeFile(OUTPUT_FILE, moduleContent, "utf-8")
  
  console.log()
  console.log("=" .repeat(50))
  console.log(`✅ Generated ${agentDefinitions.length} agent definitions`)
  console.log(`📄 Output: ${OUTPUT_FILE}`)
  console.log()
  console.log("🚀 Next steps:")
  console.log("   1. Import from '@agentpod/agents/generated'")
  console.log("   2. Use ensureDefaultAgents(userId) on user creation")
  console.log()
}

main().catch((error) => {
  console.error("❌ Error:", error)
  process.exit(1)
})
