import type { ThemePreset } from "../types";

export const oceanBreeze: ThemePreset = {
  id: "ocean-breeze",
  label: "Ocean Breeze",
  category: "nature",
  fonts: {
    "font-body": "Source Sans 3",
    "font-heading": "Raleway",
    "font-mono": "Source Code Pro",
  },
  styles: {
    light: {
      background: "#f0f9ff",
      foreground: "#0c4a6e",
      card: "#ffffff",
      "card-foreground": "#0c4a6e",
      popover: "#ffffff",
      "popover-foreground": "#0c4a6e",
      primary: "#0369a1",
      "primary-foreground": "#ffffff",
      secondary: "#e0f2fe",
      "secondary-foreground": "#0c4a6e",
      muted: "#e0f2fe",
      "muted-foreground": "#075985",
      accent: "#bae6fd",
      "accent-foreground": "#0c4a6e",
      destructive: "#dc2626",
      "destructive-foreground": "#ffffff",
      border: "#bae6fd",
      input: "#bae6fd",
      ring: "#0369a1",
      "chart-1": "#0369a1",
      "chart-2": "#0284c7",
      "chart-3": "#0ea5e9",
      "chart-4": "#38bdf8",
      "chart-5": "#7dd3fc",
      radius: "0.5rem",
      sidebar: "#f0f9ff",
      "sidebar-foreground": "#0c4a6e",
      "sidebar-primary": "#0369a1",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#bae6fd",
      "sidebar-accent-foreground": "#0c4a6e",
      "sidebar-border": "#bae6fd",
      "sidebar-ring": "#0369a1",
      "cyber-cyan": "#0369a1",
      "cyber-cyan-dim": "#075985",
      "cyber-emerald": "#0d9488",
      "cyber-magenta": "#7c3aed",
      "cyber-amber": "#f59e0b",
      "cyber-red": "#dc2626",
      "cyber-glow": "0 0 12px rgba(3, 105, 161, 0.2)",
      "cyber-glow-emerald": "0 0 12px rgba(13, 148, 136, 0.2)",
    },
    dark: {
      background: "#0c4a6e",
      foreground: "#e0f2fe",
      card: "#075985",
      "card-foreground": "#e0f2fe",
      popover: "#075985",
      "popover-foreground": "#e0f2fe",
      primary: "#38bdf8",
      "primary-foreground": "#0c4a6e",
      secondary: "#0369a1",
      "secondary-foreground": "#e0f2fe",
      muted: "#0369a1",
      "muted-foreground": "#7dd3fc",
      accent: "#0284c7",
      "accent-foreground": "#e0f2fe",
      destructive: "#f87171",
      "destructive-foreground": "#0c4a6e",
      border: "#0369a1",
      input: "#0369a1",
      ring: "#38bdf8",
      "chart-1": "#38bdf8",
      "chart-2": "#7dd3fc",
      "chart-3": "#0ea5e9",
      "chart-4": "#0284c7",
      "chart-5": "#bae6fd",
      sidebar: "#0c4a6e",
      "sidebar-foreground": "#e0f2fe",
      "sidebar-primary": "#38bdf8",
      "sidebar-primary-foreground": "#0c4a6e",
      "sidebar-accent": "#0284c7",
      "sidebar-accent-foreground": "#e0f2fe",
      "sidebar-border": "#0369a1",
      "sidebar-ring": "#38bdf8",
      "cyber-cyan": "#38bdf8",
      "cyber-cyan-dim": "#0ea5e9",
      "cyber-emerald": "#2dd4bf",
      "cyber-magenta": "#a78bfa",
      "cyber-amber": "#fbbf24",
      "cyber-red": "#f87171",
      "cyber-glow": "0 0 20px rgba(56, 189, 248, 0.3)",
      "cyber-glow-emerald": "0 0 20px rgba(45, 212, 191, 0.3)",
    },
  },
};
