import type { ThemePreset } from "../types";

export const sunsetHorizon: ThemePreset = {
  id: "sunset-horizon",
  label: "Sunset Horizon",
  category: "nature",
  fonts: {
    "font-body": "Nunito",
    "font-heading": "Poppins",
    "font-mono": "JetBrains Mono",
  },
  styles: {
    light: {
      background: "#fff9f5",
      foreground: "#3d3436",
      card: "#ffffff",
      "card-foreground": "#3d3436",
      popover: "#ffffff",
      "popover-foreground": "#3d3436",
      primary: "#ff7e5f",
      "primary-foreground": "#ffffff",
      secondary: "#ffedea",
      "secondary-foreground": "#b35340",
      muted: "#fff0eb",
      "muted-foreground": "#78716C",
      accent: "#feb47b",
      "accent-foreground": "#3d3436",
      destructive: "#e63946",
      "destructive-foreground": "#ffffff",
      border: "#ffe0d6",
      input: "#ffe0d6",
      ring: "#ff7e5f",
      "chart-1": "#ff7e5f",
      "chart-2": "#feb47b",
      "chart-3": "#ffcaa7",
      "chart-4": "#ffad8f",
      "chart-5": "#ce6a57",
      radius: "0.625rem",
      sidebar: "#fff0eb",
      "sidebar-foreground": "#3d3436",
      "sidebar-primary": "#ff7e5f",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#feb47b",
      "sidebar-accent-foreground": "#3d3436",
      "sidebar-border": "#ffe0d6",
      "sidebar-ring": "#ff7e5f",
      "cyber-cyan": "#ff7e5f",
      "cyber-cyan-dim": "#e66b50",
      "cyber-emerald": "#feb47b",
      "cyber-magenta": "#f472b6",
      "cyber-amber": "#fbbf24",
      "cyber-red": "#e63946",
      "cyber-glow": "0 0 12px rgba(255, 126, 95, 0.2)",
      "cyber-glow-emerald": "0 0 12px rgba(254, 180, 123, 0.2)",
    },
    dark: {
      background: "#2a2024",
      foreground: "#f2e9e4",
      card: "#392f35",
      "card-foreground": "#f2e9e4",
      popover: "#392f35",
      "popover-foreground": "#f2e9e4",
      primary: "#ff7e5f",
      "primary-foreground": "#ffffff",
      secondary: "#463a41",
      "secondary-foreground": "#f2e9e4",
      muted: "#392f35",
      "muted-foreground": "#d7c6bc",
      accent: "#feb47b",
      "accent-foreground": "#2a2024",
      destructive: "#e63946",
      "destructive-foreground": "#ffffff",
      border: "#463a41",
      input: "#463a41",
      ring: "#ff7e5f",
      "chart-1": "#ff7e5f",
      "chart-2": "#feb47b",
      "chart-3": "#ffcaa7",
      "chart-4": "#ffad8f",
      "chart-5": "#ce6a57",
      sidebar: "#2a2024",
      "sidebar-foreground": "#f2e9e4",
      "sidebar-primary": "#ff7e5f",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#feb47b",
      "sidebar-accent-foreground": "#2a2024",
      "sidebar-border": "#463a41",
      "sidebar-ring": "#ff7e5f",
      "cyber-cyan": "#ff9a85",
      "cyber-cyan-dim": "#ff7e5f",
      "cyber-emerald": "#feb47b",
      "cyber-magenta": "#f9a8d4",
      "cyber-amber": "#fde68a",
      "cyber-red": "#f87171",
      "cyber-glow": "0 0 20px rgba(255, 154, 133, 0.3)",
      "cyber-glow-emerald": "0 0 20px rgba(254, 180, 123, 0.3)",
    },
  },
};
