/**
 * MCP (Model Context Protocol) Server Types
 *
 * Types for managing MCP servers, namespaces, and endpoints.
 * Used with MetaMCP integration for server aggregation.
 */

// =============================================================================
// MCP Server Types
// =============================================================================

/**
 * Transport type for MCP servers
 */
export type McpServerType = "STDIO" | "SSE" | "STREAMABLE_HTTP";

/**
 * Authentication type for MCP servers
 */
export type McpAuthType =
  | "none"
  | "api_key"
  | "bearer_token"
  | "oauth2"
  | "env_vars";

/**
 * OAuth2 configuration for MCP servers
 */
export interface McpOAuth2Config {
  clientId: string;
  clientSecret?: string;
  scope?: string;
  authorizationUrl?: string;
  tokenUrl?: string;
}

/**
 * Authentication configuration for MCP servers
 */
export interface McpAuthConfig {
  type: McpAuthType;
  /** API key value (for api_key type) */
  apiKey?: string;
  /** Bearer token value (for bearer_token type) */
  bearerToken?: string;
  /** OAuth2 configuration (for oauth2 type) */
  oauth2?: McpOAuth2Config;
  /** Environment variables to inject (for env_vars type) */
  envVars?: Record<string, string>;
  /** Custom headers to include with requests */
  headers?: Record<string, string>;
}

/**
 * MCP Server configuration
 */
export interface McpServer {
  id: string;
  userId: string;
  name: string;
  description?: string;
  type: McpServerType;

  // STDIO configuration
  command?: string;
  args?: string[];

  // Remote server configuration (SSE/HTTP)
  url?: string;

  // Authentication
  auth: McpAuthConfig;

  // Environment variables (for STDIO servers)
  environment?: Record<string, string>;

  // MetaMCP sync
  metamcpServerId?: string;

  // Status
  enabled: boolean;
  isPublic: boolean;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Create MCP Server request
 */
export interface CreateMcpServerRequest {
  name: string;
  description?: string;
  type: McpServerType;
  command?: string;
  args?: string[];
  url?: string;
  auth: McpAuthConfig;
  environment?: Record<string, string>;
  isPublic?: boolean;
}

/**
 * Update MCP Server request
 */
export interface UpdateMcpServerRequest {
  name?: string;
  description?: string;
  type?: McpServerType;
  command?: string;
  args?: string[];
  url?: string;
  auth?: McpAuthConfig;
  environment?: Record<string, string>;
  enabled?: boolean;
  isPublic?: boolean;
}

// =============================================================================
// MCP Namespace Types
// =============================================================================

/**
 * MCP Namespace - groups multiple servers
 */
export interface McpNamespace {
  id: string;
  userId: string;
  name: string;
  description?: string;

  // MetaMCP sync
  metamcpNamespaceId?: string;

  // Status
  isPublic: boolean;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Server association with namespace
 */
export interface McpNamespaceServer {
  namespaceId: string;
  serverId: string;
  enabled: boolean;
}

/**
 * Tool override for namespace
 */
export interface McpToolOverride {
  id: string;
  namespaceId: string;
  serverId: string;
  toolName: string;
  enabled: boolean;
  overrideName?: string;
  overrideDescription?: string;
  annotations?: Record<string, unknown>;
}

/**
 * Create Namespace request
 */
export interface CreateMcpNamespaceRequest {
  name: string;
  description?: string;
  serverIds?: string[];
  isPublic?: boolean;
}

/**
 * Update Namespace request
 */
export interface UpdateMcpNamespaceRequest {
  name?: string;
  description?: string;
  isPublic?: boolean;
}

// =============================================================================
// MCP Endpoint Types
// =============================================================================

/**
 * Authentication type for endpoints
 */
export type McpEndpointAuthType = "api_key" | "oauth";

/**
 * MCP Endpoint - exposes a namespace via URL
 */
export interface McpEndpoint {
  id: string;
  userId: string;
  namespaceId: string;
  name: string;

  // Auth settings
  authEnabled: boolean;
  authType: McpEndpointAuthType;

  // MetaMCP sync
  metamcpEndpointId?: string;

  // Status
  isPublic: boolean;

  // Timestamps
  createdAt: string;
  updatedAt: string;
}

/**
 * Endpoint URLs (generated by MetaMCP)
 */
export interface McpEndpointUrls {
  sse: string;
  mcp: string;
  api: string;
  openapi: string;
}

/**
 * Create Endpoint request
 */
export interface CreateMcpEndpointRequest {
  name: string;
  namespaceId: string;
  authEnabled?: boolean;
  authType?: McpEndpointAuthType;
  isPublic?: boolean;
}

/**
 * Update Endpoint request
 */
export interface UpdateMcpEndpointRequest {
  name?: string;
  namespaceId?: string;
  authEnabled?: boolean;
  authType?: McpEndpointAuthType;
  isPublic?: boolean;
}

// =============================================================================
// MCP API Key Types
// =============================================================================

/**
 * API key for endpoint access
 */
export interface McpApiKey {
  id: string;
  userId: string;
  endpointId?: string;
  keyPrefix: string;
  description?: string;
  scopes: string[];
  expiresAt?: string;
  lastUsedAt?: string;
  createdAt: string;
}

/**
 * Create API Key request
 */
export interface CreateMcpApiKeyRequest {
  endpointId?: string;
  description?: string;
  scopes?: string[];
  expiresInDays?: number;
}

/**
 * API Key creation response (includes full key, shown only once)
 */
export interface McpApiKeyCreated extends McpApiKey {
  /** Full API key (only shown at creation time) */
  key: string;
}

// =============================================================================
// MCP Tool Types
// =============================================================================

/**
 * MCP Tool definition
 */
export interface McpTool {
  name: string;
  description?: string;
  serverName: string;
  inputSchema?: Record<string, unknown>;
  enabled: boolean;
}

/**
 * Tool list for namespace
 */
export interface McpNamespaceTools {
  namespaceId: string;
  tools: McpTool[];
}

// =============================================================================
// MetaMCP Sync Types
// =============================================================================

/**
 * MetaMCP connection status
 */
export type MetaMcpConnectionStatus =
  | "connected"
  | "disconnected"
  | "connecting"
  | "error";

/**
 * MetaMCP sync status
 */
export interface MetaMcpSyncStatus {
  connected: boolean;
  status: MetaMcpConnectionStatus;
  lastSyncAt?: string;
  error?: string;
  version?: string;
}

/**
 * MetaMCP configuration
 */
export interface MetaMcpConfig {
  url: string;
  apiKey?: string;
  enabled: boolean;
}

// =============================================================================
// OpenCode.json MCP Configuration
// =============================================================================

/**
 * MCP server configuration for opencode.json
 */
export interface OpenCodeMcpServerConfig {
  type: "local" | "remote";
  /** Command array for local servers */
  command?: string[];
  /** URL for remote servers */
  url?: string;
  /** Environment variables */
  environment?: Record<string, string>;
  /** HTTP headers for remote servers */
  headers?: Record<string, string>;
  /** OAuth configuration */
  oauth?: {
    clientId?: string;
    clientSecret?: string;
    scope?: string;
  } | false;
  /** Connection timeout in ms */
  timeout?: number;
  /** Whether server is enabled */
  enabled?: boolean;
}

/**
 * Generate OpenCode.json MCP configuration from namespace
 */
export interface GenerateOpenCodeMcpConfigRequest {
  namespaceId?: string;
  endpointId?: string;
  /** Include individual servers or use unified endpoint */
  useUnifiedEndpoint?: boolean;
}

/**
 * Generated MCP configuration for opencode.json
 */
export interface GenerateOpenCodeMcpConfigResponse {
  mcp: Record<string, OpenCodeMcpServerConfig>;
}

// =============================================================================
// MCP OAuth Types
// =============================================================================

export type McpOAuthStatus = "pending" | "authorized" | "expired" | "error";

export interface OAuthProtectedResourceMetadata {
  resource: string;
  authorization_servers?: string[];
  bearer_methods_supported?: string[];
  scopes_supported?: string[];
}

export interface OAuthAuthorizationServerMetadata {
  issuer: string;
  authorization_endpoint: string;
  token_endpoint: string;
  registration_endpoint?: string;
  jwks_uri?: string | null;
  response_types_supported?: string[];
  grant_types_supported?: string[];
  code_challenge_methods_supported?: string[];
  token_endpoint_auth_methods_supported?: string[];
  scopes_supported?: string[];
}

export interface McpOAuthDiscoveryResult {
  requiresOAuth: boolean;
  resourceMetadata?: OAuthProtectedResourceMetadata;
  authServerMetadata?: OAuthAuthorizationServerMetadata;
  error?: string;
}

export interface McpOAuthSession {
  id: string;
  mcpServerId: string;
  userId: string;
  resourceUrl?: string;
  authorizationServerUrl?: string;
  clientId?: string;
  tokenType?: string;
  expiresAt?: string;
  scope?: string;
  status: McpOAuthStatus;
  errorMessage?: string;
  createdAt: string;
  updatedAt: string;
}

export interface McpOAuthInitiateRequest {
  mcpServerId: string;
  redirectUri?: string;
}

export interface McpOAuthInitiateResponse {
  authorizationUrl: string;
  state: string;
}

export interface McpOAuthCallbackRequest {
  code: string;
  state: string;
}

export interface McpOAuthCallbackResponse {
  success: boolean;
  mcpServerId?: string;
  error?: string;
}

export interface McpOAuthStatusResponse {
  status: McpOAuthStatus;
  expiresAt?: string;
  scope?: string;
  errorMessage?: string;
}
