import type { ThemePreset } from "../types";

export const catppuccin: ThemePreset = {
  id: "catppuccin",
  label: "Catppuccin",
  category: "developer",
  fonts: {
    "font-body": "Nunito",
    "font-heading": "Nunito",
    "font-mono": "JetBrains Mono",
  },
  styles: {
    light: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      card: "#ffffff",
      "card-foreground": "#4c4f69",
      popover: "#ccd0da",
      "popover-foreground": "#4c4f69",
      primary: "#8839ef",
      "primary-foreground": "#ffffff",
      secondary: "#ccd0da",
      "secondary-foreground": "#4c4f69",
      muted: "#dce0e8",
      "muted-foreground": "#4f5268",
      accent: "#04a5e5",
      "accent-foreground": "#1e1e2e",
      destructive: "#d20f39",
      "destructive-foreground": "#ffffff",
      border: "#bcc0cc",
      input: "#ccd0da",
      ring: "#8839ef",
      "chart-1": "#8839ef",
      "chart-2": "#04a5e5",
      "chart-3": "#40a02b",
      "chart-4": "#fe640b",
      "chart-5": "#dc8a78",
      radius: "0.35rem",
      sidebar: "#e6e9ef",
      "sidebar-foreground": "#4c4f69",
      "sidebar-primary": "#8839ef",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#04a5e5",
      "sidebar-accent-foreground": "#1e1e2e",
      "sidebar-border": "#bcc0cc",
      "sidebar-ring": "#8839ef",
      "cyber-cyan": "#0369a1",
      "cyber-cyan-dim": "#0282b5",
      "cyber-emerald": "#2d7a20",
      "cyber-magenta": "#8839ef",
      "cyber-amber": "#8a4007",
      "cyber-red": "#d20f39",
      "cyber-glow": "0 0 12px rgba(4, 165, 229, 0.2)",
      "cyber-glow-emerald": "0 0 12px rgba(64, 160, 43, 0.2)",
    },
    dark: {
      background: "#181825",
      foreground: "#cdd6f4",
      card: "#1e1e2e",
      "card-foreground": "#cdd6f4",
      popover: "#45475a",
      "popover-foreground": "#cdd6f4",
      primary: "#cba6f7",
      "primary-foreground": "#1e1e2e",
      secondary: "#585b70",
      "secondary-foreground": "#cdd6f4",
      muted: "#292c3c",
      "muted-foreground": "#a6adc8",
      accent: "#89dceb",
      "accent-foreground": "#1e1e2e",
      destructive: "#f38ba8",
      "destructive-foreground": "#1e1e2e",
      border: "#313244",
      input: "#313244",
      ring: "#cba6f7",
      "chart-1": "#cba6f7",
      "chart-2": "#89dceb",
      "chart-3": "#a6e3a1",
      "chart-4": "#fab387",
      "chart-5": "#f5e0dc",
      sidebar: "#11111b",
      "sidebar-foreground": "#cdd6f4",
      "sidebar-primary": "#cba6f7",
      "sidebar-primary-foreground": "#1e1e2e",
      "sidebar-accent": "#89dceb",
      "sidebar-accent-foreground": "#1e1e2e",
      "sidebar-border": "#45475a",
      "sidebar-ring": "#cba6f7",
      "cyber-cyan": "#89dceb",
      "cyber-cyan-dim": "#6bc4d6",
      "cyber-emerald": "#a6e3a1",
      "cyber-magenta": "#cba6f7",
      "cyber-amber": "#fab387",
      "cyber-red": "#f38ba8",
      "cyber-glow": "0 0 20px rgba(137, 220, 235, 0.3)",
      "cyber-glow-emerald": "0 0 20px rgba(166, 227, 161, 0.3)",
    },
  },
};
