import type { ThemePreset } from "../types";

export const cosmicNight: ThemePreset = {
  id: "cosmic-night",
  label: "Cosmic Night",
  category: "developer",
  fonts: {
    "font-body": "Exo 2",
    "font-heading": "Orbitron",
    "font-mono": "Fira Code",
  },
  styles: {
    light: {
      background: "#f5f5ff",
      foreground: "#2a2a4a",
      card: "#ffffff",
      "card-foreground": "#2a2a4a",
      popover: "#ffffff",
      "popover-foreground": "#2a2a4a",
      primary: "#6e56cf",
      "primary-foreground": "#ffffff",
      secondary: "#e4dfff",
      "secondary-foreground": "#4a4080",
      muted: "#f0f0fa",
      "muted-foreground": "#6c6c8a",
      accent: "#d8e6ff",
      "accent-foreground": "#2a2a4a",
      destructive: "#ff5470",
      "destructive-foreground": "#ffffff",
      border: "#e0e0f0",
      input: "#e0e0f0",
      ring: "#6e56cf",
      "chart-1": "#6e56cf",
      "chart-2": "#9e8cfc",
      "chart-3": "#5d5fef",
      "chart-4": "#7c75fa",
      "chart-5": "#4740b3",
      radius: "0.5rem",
      sidebar: "#f0f0fa",
      "sidebar-foreground": "#2a2a4a",
      "sidebar-primary": "#6e56cf",
      "sidebar-primary-foreground": "#ffffff",
      "sidebar-accent": "#d8e6ff",
      "sidebar-accent-foreground": "#2a2a4a",
      "sidebar-border": "#e0e0f0",
      "sidebar-ring": "#6e56cf",
      "cyber-cyan": "#6e56cf",
      "cyber-cyan-dim": "#5842b0",
      "cyber-emerald": "#5d5fef",
      "cyber-magenta": "#9e8cfc",
      "cyber-amber": "#f59e0b",
      "cyber-red": "#ff5470",
      "cyber-glow": "0 0 12px rgba(110, 86, 207, 0.2)",
      "cyber-glow-emerald": "0 0 12px rgba(93, 95, 239, 0.2)",
    },
    dark: {
      background: "#0f0f1a",
      foreground: "#e2e2f5",
      card: "#1a1a2e",
      "card-foreground": "#e2e2f5",
      popover: "#1a1a2e",
      "popover-foreground": "#e2e2f5",
      primary: "#a48fff",
      "primary-foreground": "#0f0f1a",
      secondary: "#2d2b55",
      "secondary-foreground": "#c4c2ff",
      muted: "#222244",
      "muted-foreground": "#a0a0c0",
      accent: "#303060",
      "accent-foreground": "#e2e2f5",
      destructive: "#ff5470",
      "destructive-foreground": "#ffffff",
      border: "#303052",
      input: "#303052",
      ring: "#a48fff",
      "chart-1": "#a48fff",
      "chart-2": "#7986cb",
      "chart-3": "#64b5f6",
      "chart-4": "#4db6ac",
      "chart-5": "#ff79c6",
      sidebar: "#1a1a2e",
      "sidebar-foreground": "#e2e2f5",
      "sidebar-primary": "#a48fff",
      "sidebar-primary-foreground": "#0f0f1a",
      "sidebar-accent": "#303060",
      "sidebar-accent-foreground": "#e2e2f5",
      "sidebar-border": "#303052",
      "sidebar-ring": "#a48fff",
      "cyber-cyan": "#a48fff",
      "cyber-cyan-dim": "#8b7ae8",
      "cyber-emerald": "#64b5f6",
      "cyber-magenta": "#ff79c6",
      "cyber-amber": "#fbbf24",
      "cyber-red": "#ff5470",
      "cyber-glow": "0 0 20px rgba(164, 143, 255, 0.3)",
      "cyber-glow-emerald": "0 0 20px rgba(100, 181, 246, 0.3)",
    },
  },
};
