import type { ThemePreset } from "../types";

export const cyberpunk: ThemePreset = {
  id: "cyberpunk",
  label: "Cyberpunk",
  category: "creative",
  fonts: {
    "font-body": "Rajdhani",
    "font-heading": "Orbitron",
    "font-mono": "JetBrains Mono",
  },
  styles: {
    light: {
      background: "#f8f9fa",
      foreground: "#0c0c1d",
      card: "#ffffff",
      "card-foreground": "#0c0c1d",
      popover: "#ffffff",
      "popover-foreground": "#0c0c1d",
      primary: "#ff00c8",
      "primary-foreground": "#1a0014",
      secondary: "#f0f0ff",
      "secondary-foreground": "#0c0c1d",
      muted: "#f0f0ff",
      "muted-foreground": "#0c0c1d",
      accent: "#00ffcc",
      "accent-foreground": "#0c0c1d",
      destructive: "#ff3d00",
      "destructive-foreground": "#1a0800",
      border: "#dfe6e9",
      input: "#dfe6e9",
      ring: "#ff00c8",
      "chart-1": "#ff00c8",
      "chart-2": "#9000ff",
      "chart-3": "#00e5ff",
      "chart-4": "#00ffcc",
      "chart-5": "#ffe600",
      radius: "0.5rem",
      sidebar: "#f0f0ff",
      "sidebar-foreground": "#0c0c1d",
      "sidebar-primary": "#ff00c8",
      "sidebar-primary-foreground": "#1a0014",
      "sidebar-accent": "#00ffcc",
      "sidebar-accent-foreground": "#0c0c1d",
      "sidebar-border": "#dfe6e9",
      "sidebar-ring": "#ff00c8",
      "cyber-cyan": "#0e7490",
      "cyber-cyan-dim": "#008888",
      "cyber-emerald": "#0a7050",
      "cyber-magenta": "#cc00a8",
      "cyber-amber": "#8a6d00",
      "cyber-red": "#c52a00",
      "cyber-glow": "0 0 12px rgba(0, 184, 184, 0.3)",
      "cyber-glow-emerald": "0 0 12px rgba(0, 204, 136, 0.3)",
    },
    dark: {
      background: "#0c0c1d",
      foreground: "#eceff4",
      card: "#1e1e3f",
      "card-foreground": "#eceff4",
      popover: "#1e1e3f",
      "popover-foreground": "#eceff4",
      primary: "#ff00c8",
      "primary-foreground": "#1a0014",
      secondary: "#1e1e3f",
      "secondary-foreground": "#eceff4",
      muted: "#1e1e3f",
      "muted-foreground": "#a0a5c5",
      accent: "#00ffcc",
      "accent-foreground": "#0c0c1d",
      destructive: "#ff3d00",
      "destructive-foreground": "#1a0800",
      border: "#2e2e5e",
      input: "#2e2e5e",
      ring: "#ff00c8",
      "chart-1": "#ff00c8",
      "chart-2": "#9000ff",
      "chart-3": "#00e5ff",
      "chart-4": "#00ffcc",
      "chart-5": "#ffe600",
      sidebar: "#0c0c1d",
      "sidebar-foreground": "#eceff4",
      "sidebar-primary": "#ff00c8",
      "sidebar-primary-foreground": "#1a0014",
      "sidebar-accent": "#00ffcc",
      "sidebar-accent-foreground": "#0c0c1d",
      "sidebar-border": "#2e2e5e",
      "sidebar-ring": "#ff00c8",
      "cyber-cyan": "#00ffff",
      "cyber-cyan-dim": "#00cccc",
      "cyber-emerald": "#00ffcc",
      "cyber-magenta": "#ff00c8",
      "cyber-amber": "#ffe600",
      "cyber-red": "#ff3d00",
      "cyber-glow": "0 0 25px rgba(0, 255, 255, 0.4)",
      "cyber-glow-emerald": "0 0 25px rgba(0, 255, 204, 0.4)",
    },
  },
};
